Remove two cookbooks that no longer clone down cleanly. Seems like a git bug?
$ git clone -q https://github.com/chef-cookbooks/freebsd.git
error: object 4f7d61a2f4f6e98675dab5cb32f55239f1c591b3: zeroPaddedFilemode: contains zero-padded file modes
fatal: Error in object
fatal: index-pack failed